# Veritaban? URL'i (kendi_veritabani_adin k?sm?n? de?i?tir)
spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=DB_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true